import Column from '@/components/Column/Column'
import Head from 'next/head'
import Image from 'next/image'

export default function Home(props) {
  const {data} = props;
  if(!data){
    return <div>Loading...</div>
  }
  const column = data.map((e, i) => {
    return <Column key={i} day={e.day} amount={e.amount} />
  });

  return (
    <>
      <Head>
        <title>Expenses Chart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main>
        <div className="container center">
          <div className="balanceHead">
            <div className="balance">
              <p>My Balance</p>
              <h1 id="balanceVal">$921.48</h1>
            </div>
            <Image className='logo' src={'./logo.svg'} width={100} height={100} />
          </div>
          <div className="bodySection">
            <h2>Spending - Last 7 days</h2>
            <div className="chart center">
              {/* <Column />
              <Column />
              <Column />
              <Column />
              <Column />
              <Column />
              <Column /> */}
              column();
            </div>
            <div className="divider"></div>
            <div className="bottom center" style={{justifyContent: 'space-between'}}>
              <div className="thisMonth">
                <p style={{color: 'var(--MediumBrown)'}}>Total this month</p>
                <h1>$478.33</h1>
              </div>
              <div className="lastMonth">
                <p style={{fontWeight: '700'}}>+2.4%</p>
                <p style={{color: 'var(--MediumBrown)'}}>from last month</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}


export async function getStaticProps(){
  const response = await fetch("http://localhost:3000/api/expenses");
  const data = await response.json();
  return{
    props: {
      data: data
    }
  };
}